import { Footer, Navbar } from "@/components";
import "./globals.scss";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body>
                <Navbar />
                {children}
                <Footer />
            </body>
        </html>
    );
}
